//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace integraMobile.WS.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("integraMobile.WS.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILESYSTEM.
        /// </summary>
        internal static string Activation_EmailBody {
            get {
                return ResourceManager.GetString("Activation_EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BILBAOPARK: Activación de cuenta.
        /// </summary>
        internal static string Activation_EmailBody_Subject {
            get {
                return ResourceManager.GetString("Activation_EmailBody_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro de BILBAOPARK.
        /// </summary>
        internal static string Activation_EmailHeader {
            get {
                return ResourceManager.GetString("Activation_EmailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este es un mensaje de BILBAOPARK. Su codigo de activacion es {0}..
        /// </summary>
        internal static string Activation_SMS {
            get {
                return ResourceManager.GetString("Activation_SMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILESYSTEM.
        /// </summary>
        internal static string Confirm_EmailBody_Balance {
            get {
                return ResourceManager.GetString("Confirm_EmailBody_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BILBAOPARK: Recarga Automática realizada.
        /// </summary>
        internal static string ConfirmAutomaticRecharge_EmailHeader {
            get {
                return ResourceManager.GetString("ConfirmAutomaticRecharge_EmailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BILBAOPARK: Recarga realizada.
        /// </summary>
        internal static string ConfirmNoAutomaticRecharge_EmailHeader {
            get {
                return ResourceManager.GetString("ConfirmNoAutomaticRecharge_EmailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILESYSTEM.
        /// </summary>
        internal static string ConfirmOffstreet_EmailBody {
            get {
                return ResourceManager.GetString("ConfirmOffstreet_EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILESYSTEM.
        /// </summary>
        internal static string ConfirmOffstreet_EmailBody_Balance {
            get {
                return ResourceManager.GetString("ConfirmOffstreet_EmailBody_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estacionamiento realizado.
        /// </summary>
        internal static string ConfirmOffstreet_EmailHeader {
            get {
                return ResourceManager.GetString("ConfirmOffstreet_EmailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILESYSTEM.
        /// </summary>
        internal static string ConfirmParking_EmailBody {
            get {
                return ResourceManager.GetString("ConfirmParking_EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILESYSTEM.
        /// </summary>
        internal static string ConfirmParking_EmailBody_SpaceSection {
            get {
                return ResourceManager.GetString("ConfirmParking_EmailBody_SpaceSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BILBAOPARK: Justificante de Estacionamiento.
        /// </summary>
        internal static string ConfirmParking_EmailHeader {
            get {
                return ResourceManager.GetString("ConfirmParking_EmailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILESYSTEM.
        /// </summary>
        internal static string ConfirmRecharge_EmailBody {
            get {
                return ResourceManager.GetString("ConfirmRecharge_EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILESYSTEM.
        /// </summary>
        internal static string ConfirmTicketPayment_EmailBody {
            get {
                return ResourceManager.GetString("ConfirmTicketPayment_EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BILBAOPARK: Justificante de Cancelación de Denuncia.
        /// </summary>
        internal static string ConfirmTicketPayment_EmailHeader {
            get {
                return ResourceManager.GetString("ConfirmTicketPayment_EmailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILESYSTEM.
        /// </summary>
        internal static string ConfirmUnParking_EmailBody {
            get {
                return ResourceManager.GetString("ConfirmUnParking_EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BILBAOPARK: Justificante de Desaparcamiento.
        /// </summary>
        internal static string ConfirmUnParking_EmailHeader {
            get {
                return ResourceManager.GetString("ConfirmUnParking_EmailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILESYSTEM.
        /// </summary>
        internal static string CustomerInscriptionModel_SummaryWelcomeEmail_Body {
            get {
                return ResourceManager.GetString("CustomerInscriptionModel_SummaryWelcomeEmail_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenida / Bienvenido a BILBAOPARK.
        /// </summary>
        internal static string CustomerInscriptionModel_SummaryWelcomeEmail_Subject {
            get {
                return ResourceManager.GetString("CustomerInscriptionModel_SummaryWelcomeEmail_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILESYSTEM.
        /// </summary>
        internal static string DeleteUserEmail_Body {
            get {
                return ResourceManager.GetString("DeleteUserEmail_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BILBAOPARK: Notificación baja.
        /// </summary>
        internal static string DeleteUserEmail_Subject {
            get {
                return ResourceManager.GetString("DeleteUserEmail_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILESYSTEM.
        /// </summary>
        internal static string Email_LayoutSubtotal {
            get {
                return ResourceManager.GetString("Email_LayoutSubtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILESYSTEM.
        /// </summary>
        internal static string Email_LayoutTotal {
            get {
                return ResourceManager.GetString("Email_LayoutTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILESYSTEM.
        /// </summary>
        internal static string Email_LayoutTotalBonus {
            get {
                return ResourceManager.GetString("Email_LayoutTotalBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILESYSTEM.
        /// </summary>
        internal static string ExternalTicket_EmailBody {
            get {
                return ResourceManager.GetString("ExternalTicket_EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BILBAOPARK: {0} ha sido denunciado con expediente {1}.
        /// </summary>
        internal static string ExternalTicket_EmailHeader {
            get {
                return ResourceManager.GetString("ExternalTicket_EmailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILESYSTEM.
        /// </summary>
        internal static string ExternalTicketNotPayable_EmailBody {
            get {
                return ResourceManager.GetString("ExternalTicketNotPayable_EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Olvidó su usuario de BILBAOPARK? .
        /// </summary>
        internal static string ForgetUsername_EmailHeader {
            get {
                return ResourceManager.GetString("ForgetUsername_EmailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILESYSTEM.
        /// </summary>
        internal static string ForgeUsername_EmailBody {
            get {
                return ResourceManager.GetString("ForgeUsername_EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILESYSTEM.
        /// </summary>
        internal static string ForgotPassword_EmailBody {
            get {
                return ResourceManager.GetString("ForgotPassword_EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BILBAOPARK: Recuperación de contraseña.
        /// </summary>
        internal static string ForgotPassword_EmailHeader {
            get {
                return ResourceManager.GetString("ForgotPassword_EmailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este es un mensaje de BILBAOPARK. Su codigo para la recuperación de la contraseña es  {0}..
        /// </summary>
        internal static string ForgotPassword_SMS {
            get {
                return ResourceManager.GetString("ForgotPassword_SMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILESYSTEM.
        /// </summary>
        internal static string InviteFriend_Email_Body {
            get {
                return ResourceManager.GetString("InviteFriend_Email_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILESYSTEM.
        /// </summary>
        internal static string NewUserWithoutPaymentMeanEmail_Body {
            get {
                return ResourceManager.GetString("NewUserWithoutPaymentMeanEmail_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenida / Bienvenido a BILBAOPARK.
        /// </summary>
        internal static string NewUserWithoutPaymentMeanEmail_Subject {
            get {
                return ResourceManager.GetString("NewUserWithoutPaymentMeanEmail_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sector Azul.
        /// </summary>
        internal static string Sector_60001 {
            get {
                return ResourceManager.GetString("Sector_60001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sector Verde.
        /// </summary>
        internal static string Sector_60002 {
            get {
                return ResourceManager.GetString("Sector_60002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sector Azul.
        /// </summary>
        internal static string Sector_60003 {
            get {
                return ResourceManager.GetString("Sector_60003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sector Verde.
        /// </summary>
        internal static string Sector_60004 {
            get {
                return ResourceManager.GetString("Sector_60004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sector Azul.
        /// </summary>
        internal static string Sector_60005 {
            get {
                return ResourceManager.GetString("Sector_60005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sector Verde.
        /// </summary>
        internal static string Sector_60006 {
            get {
                return ResourceManager.GetString("Sector_60006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sector Azul.
        /// </summary>
        internal static string Sector_60007 {
            get {
                return ResourceManager.GetString("Sector_60007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sector Verde.
        /// </summary>
        internal static string Sector_60008 {
            get {
                return ResourceManager.GetString("Sector_60008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sector Azul.
        /// </summary>
        internal static string Sector_60009 {
            get {
                return ResourceManager.GetString("Sector_60009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sector Verde.
        /// </summary>
        internal static string Sector_60010 {
            get {
                return ResourceManager.GetString("Sector_60010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sector Azul.
        /// </summary>
        internal static string Sector_60011 {
            get {
                return ResourceManager.GetString("Sector_60011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sector Verde.
        /// </summary>
        internal static string Sector_60012 {
            get {
                return ResourceManager.GetString("Sector_60012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sector Azul.
        /// </summary>
        internal static string Sector_60013 {
            get {
                return ResourceManager.GetString("Sector_60013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sector Verde.
        /// </summary>
        internal static string Sector_60014 {
            get {
                return ResourceManager.GetString("Sector_60014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sector Azul.
        /// </summary>
        internal static string Sector_60015 {
            get {
                return ResourceManager.GetString("Sector_60015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sector Verde.
        /// </summary>
        internal static string Sector_60016 {
            get {
                return ResourceManager.GetString("Sector_60016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sector Azul.
        /// </summary>
        internal static string Sector_60017 {
            get {
                return ResourceManager.GetString("Sector_60017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sector Verde.
        /// </summary>
        internal static string Sector_60018 {
            get {
                return ResourceManager.GetString("Sector_60018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sector Azul.
        /// </summary>
        internal static string Sector_60019 {
            get {
                return ResourceManager.GetString("Sector_60019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sector Verde.
        /// </summary>
        internal static string Sector_60020 {
            get {
                return ResourceManager.GetString("Sector_60020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sector Azul.
        /// </summary>
        internal static string Sector_60021 {
            get {
                return ResourceManager.GetString("Sector_60021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sector Verde.
        /// </summary>
        internal static string Sector_60022 {
            get {
                return ResourceManager.GetString("Sector_60022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sector Azul.
        /// </summary>
        internal static string Sector_60023 {
            get {
                return ResourceManager.GetString("Sector_60023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sector Verde.
        /// </summary>
        internal static string Sector_60024 {
            get {
                return ResourceManager.GetString("Sector_60024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sector Azul.
        /// </summary>
        internal static string Sector_60027 {
            get {
                return ResourceManager.GetString("Sector_60027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sector Verde.
        /// </summary>
        internal static string Sector_60028 {
            get {
                return ResourceManager.GetString("Sector_60028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sector Verde L.
        /// </summary>
        internal static string Sector_60029 {
            get {
                return ResourceManager.GetString("Sector_60029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sector Azul.
        /// </summary>
        internal static string Sector_A {
            get {
                return ResourceManager.GetString("Sector_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sector Verde.
        /// </summary>
        internal static string Sector_V {
            get {
                return ResourceManager.GetString("Sector_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sector Verde L.
        /// </summary>
        internal static string Sector_VL {
            get {
                return ResourceManager.GetString("Sector_VL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILESYSTEM.
        /// </summary>
        internal static string TransferBalanceDst_EmailBody {
            get {
                return ResourceManager.GetString("TransferBalanceDst_EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BILBAOPARK: Transferencia de Saldo Recibida.
        /// </summary>
        internal static string TransferBalanceDst_EmailHeader {
            get {
                return ResourceManager.GetString("TransferBalanceDst_EmailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILESYSTEM.
        /// </summary>
        internal static string TransferBalanceSrc_EmailBody {
            get {
                return ResourceManager.GetString("TransferBalanceSrc_EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BILBAOPARK: Transferencia de Saldo Enviada.
        /// </summary>
        internal static string TransferBalanceSrc_EmailHeader {
            get {
                return ResourceManager.GetString("TransferBalanceSrc_EmailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 01 - Abando.
        /// </summary>
        internal static string Zone_60001 {
            get {
                return ResourceManager.GetString("Zone_60001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 01 - Abando.
        /// </summary>
        internal static string Zone_60002 {
            get {
                return ResourceManager.GetString("Zone_60002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 02 - Indautxu A.
        /// </summary>
        internal static string Zone_60003 {
            get {
                return ResourceManager.GetString("Zone_60003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 02 - Indautxu A.
        /// </summary>
        internal static string Zone_60004 {
            get {
                return ResourceManager.GetString("Zone_60004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 03 - Indautxu B.
        /// </summary>
        internal static string Zone_60005 {
            get {
                return ResourceManager.GetString("Zone_60005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 03 - Indautxu B.
        /// </summary>
        internal static string Zone_60006 {
            get {
                return ResourceManager.GetString("Zone_60006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 04 - Ametzola.
        /// </summary>
        internal static string Zone_60007 {
            get {
                return ResourceManager.GetString("Zone_60007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 04 - Ametzola.
        /// </summary>
        internal static string Zone_60008 {
            get {
                return ResourceManager.GetString("Zone_60008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 05 - Basurtu.
        /// </summary>
        internal static string Zone_60009 {
            get {
                return ResourceManager.GetString("Zone_60009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 05 - Basurtu.
        /// </summary>
        internal static string Zone_60010 {
            get {
                return ResourceManager.GetString("Zone_60010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 6 - Errekaldeberri.
        /// </summary>
        internal static string Zone_60011 {
            get {
                return ResourceManager.GetString("Zone_60011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 6 - Errekaldeberri.
        /// </summary>
        internal static string Zone_60012 {
            get {
                return ResourceManager.GetString("Zone_60012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 07 - Iralabarri.
        /// </summary>
        internal static string Zone_60013 {
            get {
                return ResourceManager.GetString("Zone_60013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 07 - Iralabarri.
        /// </summary>
        internal static string Zone_60014 {
            get {
                return ResourceManager.GetString("Zone_60014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 08 - Deustu.
        /// </summary>
        internal static string Zone_60015 {
            get {
                return ResourceManager.GetString("Zone_60015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 08 - Deustu.
        /// </summary>
        internal static string Zone_60016 {
            get {
                return ResourceManager.GetString("Zone_60016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 9 - Castaños-Matiko.
        /// </summary>
        internal static string Zone_60017 {
            get {
                return ResourceManager.GetString("Zone_60017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 9 - Castaños-Matiko.
        /// </summary>
        internal static string Zone_60018 {
            get {
                return ResourceManager.GetString("Zone_60018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 10 - Casco Viejo.
        /// </summary>
        internal static string Zone_60019 {
            get {
                return ResourceManager.GetString("Zone_60019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 10 - Casco Viejo.
        /// </summary>
        internal static string Zone_60020 {
            get {
                return ResourceManager.GetString("Zone_60020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 10A - Begoña.
        /// </summary>
        internal static string Zone_60021 {
            get {
                return ResourceManager.GetString("Zone_60021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 10A - Begoña.
        /// </summary>
        internal static string Zone_60022 {
            get {
                return ResourceManager.GetString("Zone_60022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 11 - Santutxu.
        /// </summary>
        internal static string Zone_60023 {
            get {
                return ResourceManager.GetString("Zone_60023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 11 - Santutxu.
        /// </summary>
        internal static string Zone_60024 {
            get {
                return ResourceManager.GetString("Zone_60024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 12 - Ibaiondo.
        /// </summary>
        internal static string Zone_60027 {
            get {
                return ResourceManager.GetString("Zone_60027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 12 - Ibaiondo.
        /// </summary>
        internal static string Zone_60028 {
            get {
                return ResourceManager.GetString("Zone_60028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 12 - Ibaiondo.
        /// </summary>
        internal static string Zone_60029 {
            get {
                return ResourceManager.GetString("Zone_60029", resourceCulture);
            }
        }
    }
}
