//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace integraMobile.ExternalWS.MeyparThirdPartyOffstreetWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="InterfazPublicaWebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class InterfazPublicaWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AlohaOperationCompleted;
        
        private System.Threading.SendOrPostCallback thirdpnotifycarentrymanualOperationCompleted;
        
        private System.Threading.SendOrPostCallback thirdpregisterdiscountinadvanceOperationCompleted;
        
        private System.Threading.SendOrPostCallback thirdpquerycarexitforpaymentOperationCompleted;
        
        private System.Threading.SendOrPostCallback thirdpnotifycarpaymentOperationCompleted;
        
        private System.Threading.SendOrPostCallback thirdPQueryCarDiscountforPaymentOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegistrarDescuentoNotificadoOnlineOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegistrarDescuentoNotificadoOnlineVinculadoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public InterfazPublicaWebService() {
            this.Url = global::integraMobile.ExternalWS.Properties.Settings.Default.integraMobile_ExternalWS_MeyparThirdPartyOffstreetWS_InterfazPublicaWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AlohaCompletedEventHandler AlohaCompleted;
        
        /// <remarks/>
        public event thirdpnotifycarentrymanualCompletedEventHandler thirdpnotifycarentrymanualCompleted;
        
        /// <remarks/>
        public event thirdpregisterdiscountinadvanceCompletedEventHandler thirdpregisterdiscountinadvanceCompleted;
        
        /// <remarks/>
        public event thirdpquerycarexitforpaymentCompletedEventHandler thirdpquerycarexitforpaymentCompleted;
        
        /// <remarks/>
        public event thirdpnotifycarpaymentCompletedEventHandler thirdpnotifycarpaymentCompleted;
        
        /// <remarks/>
        public event thirdPQueryCarDiscountforPaymentCompletedEventHandler thirdPQueryCarDiscountforPaymentCompleted;
        
        /// <remarks/>
        public event RegistrarDescuentoNotificadoOnlineCompletedEventHandler RegistrarDescuentoNotificadoOnlineCompleted;
        
        /// <remarks/>
        public event RegistrarDescuentoNotificadoOnlineVinculadoCompletedEventHandler RegistrarDescuentoNotificadoOnlineVinculadoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Aloha", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Aloha() {
            object[] results = this.Invoke("Aloha", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AlohaAsync() {
            this.AlohaAsync(null);
        }
        
        /// <remarks/>
        public void AlohaAsync(object userState) {
            if ((this.AlohaOperationCompleted == null)) {
                this.AlohaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAlohaOperationCompleted);
            }
            this.InvokeAsync("Aloha", new object[0], this.AlohaOperationCompleted, userState);
        }
        
        private void OnAlohaOperationCompleted(object arg) {
            if ((this.AlohaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AlohaCompleted(this, new AlohaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/thirdpnotifycarentrymanual", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string thirdpnotifycarentrymanual(string xmlin) {
            object[] results = this.Invoke("thirdpnotifycarentrymanual", new object[] {
                        xmlin});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void thirdpnotifycarentrymanualAsync(string xmlin) {
            this.thirdpnotifycarentrymanualAsync(xmlin, null);
        }
        
        /// <remarks/>
        public void thirdpnotifycarentrymanualAsync(string xmlin, object userState) {
            if ((this.thirdpnotifycarentrymanualOperationCompleted == null)) {
                this.thirdpnotifycarentrymanualOperationCompleted = new System.Threading.SendOrPostCallback(this.OnthirdpnotifycarentrymanualOperationCompleted);
            }
            this.InvokeAsync("thirdpnotifycarentrymanual", new object[] {
                        xmlin}, this.thirdpnotifycarentrymanualOperationCompleted, userState);
        }
        
        private void OnthirdpnotifycarentrymanualOperationCompleted(object arg) {
            if ((this.thirdpnotifycarentrymanualCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.thirdpnotifycarentrymanualCompleted(this, new thirdpnotifycarentrymanualCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/thirdpregisterdiscountinadvance", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string thirdpregisterdiscountinadvance(string xmlin) {
            object[] results = this.Invoke("thirdpregisterdiscountinadvance", new object[] {
                        xmlin});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void thirdpregisterdiscountinadvanceAsync(string xmlin) {
            this.thirdpregisterdiscountinadvanceAsync(xmlin, null);
        }
        
        /// <remarks/>
        public void thirdpregisterdiscountinadvanceAsync(string xmlin, object userState) {
            if ((this.thirdpregisterdiscountinadvanceOperationCompleted == null)) {
                this.thirdpregisterdiscountinadvanceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnthirdpregisterdiscountinadvanceOperationCompleted);
            }
            this.InvokeAsync("thirdpregisterdiscountinadvance", new object[] {
                        xmlin}, this.thirdpregisterdiscountinadvanceOperationCompleted, userState);
        }
        
        private void OnthirdpregisterdiscountinadvanceOperationCompleted(object arg) {
            if ((this.thirdpregisterdiscountinadvanceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.thirdpregisterdiscountinadvanceCompleted(this, new thirdpregisterdiscountinadvanceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/thirdpquerycarexitforpayment", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string thirdpquerycarexitforpayment(string xmlin) {
            object[] results = this.Invoke("thirdpquerycarexitforpayment", new object[] {
                        xmlin});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void thirdpquerycarexitforpaymentAsync(string xmlin) {
            this.thirdpquerycarexitforpaymentAsync(xmlin, null);
        }
        
        /// <remarks/>
        public void thirdpquerycarexitforpaymentAsync(string xmlin, object userState) {
            if ((this.thirdpquerycarexitforpaymentOperationCompleted == null)) {
                this.thirdpquerycarexitforpaymentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnthirdpquerycarexitforpaymentOperationCompleted);
            }
            this.InvokeAsync("thirdpquerycarexitforpayment", new object[] {
                        xmlin}, this.thirdpquerycarexitforpaymentOperationCompleted, userState);
        }
        
        private void OnthirdpquerycarexitforpaymentOperationCompleted(object arg) {
            if ((this.thirdpquerycarexitforpaymentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.thirdpquerycarexitforpaymentCompleted(this, new thirdpquerycarexitforpaymentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/thirdpnotifycarpayment", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string thirdpnotifycarpayment(string xmlin) {
            object[] results = this.Invoke("thirdpnotifycarpayment", new object[] {
                        xmlin});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void thirdpnotifycarpaymentAsync(string xmlin) {
            this.thirdpnotifycarpaymentAsync(xmlin, null);
        }
        
        /// <remarks/>
        public void thirdpnotifycarpaymentAsync(string xmlin, object userState) {
            if ((this.thirdpnotifycarpaymentOperationCompleted == null)) {
                this.thirdpnotifycarpaymentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnthirdpnotifycarpaymentOperationCompleted);
            }
            this.InvokeAsync("thirdpnotifycarpayment", new object[] {
                        xmlin}, this.thirdpnotifycarpaymentOperationCompleted, userState);
        }
        
        private void OnthirdpnotifycarpaymentOperationCompleted(object arg) {
            if ((this.thirdpnotifycarpaymentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.thirdpnotifycarpaymentCompleted(this, new thirdpnotifycarpaymentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/thirdPQueryCarDiscountforPayment", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string thirdPQueryCarDiscountforPayment(string xmlin) {
            object[] results = this.Invoke("thirdPQueryCarDiscountforPayment", new object[] {
                        xmlin});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void thirdPQueryCarDiscountforPaymentAsync(string xmlin) {
            this.thirdPQueryCarDiscountforPaymentAsync(xmlin, null);
        }
        
        /// <remarks/>
        public void thirdPQueryCarDiscountforPaymentAsync(string xmlin, object userState) {
            if ((this.thirdPQueryCarDiscountforPaymentOperationCompleted == null)) {
                this.thirdPQueryCarDiscountforPaymentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnthirdPQueryCarDiscountforPaymentOperationCompleted);
            }
            this.InvokeAsync("thirdPQueryCarDiscountforPayment", new object[] {
                        xmlin}, this.thirdPQueryCarDiscountforPaymentOperationCompleted, userState);
        }
        
        private void OnthirdPQueryCarDiscountforPaymentOperationCompleted(object arg) {
            if ((this.thirdPQueryCarDiscountforPaymentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.thirdPQueryCarDiscountforPaymentCompleted(this, new thirdPQueryCarDiscountforPaymentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegistrarDescuentoNotificadoOnline", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RegistrarDescuentoNotificadoOnline(string jsonIn) {
            object[] results = this.Invoke("RegistrarDescuentoNotificadoOnline", new object[] {
                        jsonIn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RegistrarDescuentoNotificadoOnlineAsync(string jsonIn) {
            this.RegistrarDescuentoNotificadoOnlineAsync(jsonIn, null);
        }
        
        /// <remarks/>
        public void RegistrarDescuentoNotificadoOnlineAsync(string jsonIn, object userState) {
            if ((this.RegistrarDescuentoNotificadoOnlineOperationCompleted == null)) {
                this.RegistrarDescuentoNotificadoOnlineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegistrarDescuentoNotificadoOnlineOperationCompleted);
            }
            this.InvokeAsync("RegistrarDescuentoNotificadoOnline", new object[] {
                        jsonIn}, this.RegistrarDescuentoNotificadoOnlineOperationCompleted, userState);
        }
        
        private void OnRegistrarDescuentoNotificadoOnlineOperationCompleted(object arg) {
            if ((this.RegistrarDescuentoNotificadoOnlineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegistrarDescuentoNotificadoOnlineCompleted(this, new RegistrarDescuentoNotificadoOnlineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegistrarDescuentoNotificadoOnlineVinculado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RegistrarDescuentoNotificadoOnlineVinculado(int pTipoSoporte, string pValorSoporte, string pJsonIn) {
            object[] results = this.Invoke("RegistrarDescuentoNotificadoOnlineVinculado", new object[] {
                        pTipoSoporte,
                        pValorSoporte,
                        pJsonIn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RegistrarDescuentoNotificadoOnlineVinculadoAsync(int pTipoSoporte, string pValorSoporte, string pJsonIn) {
            this.RegistrarDescuentoNotificadoOnlineVinculadoAsync(pTipoSoporte, pValorSoporte, pJsonIn, null);
        }
        
        /// <remarks/>
        public void RegistrarDescuentoNotificadoOnlineVinculadoAsync(int pTipoSoporte, string pValorSoporte, string pJsonIn, object userState) {
            if ((this.RegistrarDescuentoNotificadoOnlineVinculadoOperationCompleted == null)) {
                this.RegistrarDescuentoNotificadoOnlineVinculadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegistrarDescuentoNotificadoOnlineVinculadoOperationCompleted);
            }
            this.InvokeAsync("RegistrarDescuentoNotificadoOnlineVinculado", new object[] {
                        pTipoSoporte,
                        pValorSoporte,
                        pJsonIn}, this.RegistrarDescuentoNotificadoOnlineVinculadoOperationCompleted, userState);
        }
        
        private void OnRegistrarDescuentoNotificadoOnlineVinculadoOperationCompleted(object arg) {
            if ((this.RegistrarDescuentoNotificadoOnlineVinculadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegistrarDescuentoNotificadoOnlineVinculadoCompleted(this, new RegistrarDescuentoNotificadoOnlineVinculadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void AlohaCompletedEventHandler(object sender, AlohaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AlohaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AlohaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void thirdpnotifycarentrymanualCompletedEventHandler(object sender, thirdpnotifycarentrymanualCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class thirdpnotifycarentrymanualCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal thirdpnotifycarentrymanualCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void thirdpregisterdiscountinadvanceCompletedEventHandler(object sender, thirdpregisterdiscountinadvanceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class thirdpregisterdiscountinadvanceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal thirdpregisterdiscountinadvanceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void thirdpquerycarexitforpaymentCompletedEventHandler(object sender, thirdpquerycarexitforpaymentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class thirdpquerycarexitforpaymentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal thirdpquerycarexitforpaymentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void thirdpnotifycarpaymentCompletedEventHandler(object sender, thirdpnotifycarpaymentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class thirdpnotifycarpaymentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal thirdpnotifycarpaymentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void thirdPQueryCarDiscountforPaymentCompletedEventHandler(object sender, thirdPQueryCarDiscountforPaymentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class thirdPQueryCarDiscountforPaymentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal thirdPQueryCarDiscountforPaymentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void RegistrarDescuentoNotificadoOnlineCompletedEventHandler(object sender, RegistrarDescuentoNotificadoOnlineCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegistrarDescuentoNotificadoOnlineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegistrarDescuentoNotificadoOnlineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void RegistrarDescuentoNotificadoOnlineVinculadoCompletedEventHandler(object sender, RegistrarDescuentoNotificadoOnlineVinculadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegistrarDescuentoNotificadoOnlineVinculadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegistrarDescuentoNotificadoOnlineVinculadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591