//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace integraMobile.ExternalWS.integraExternalServices {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="integraExternalServicesSoap", Namespace="http://tempuri.org/")]
    public partial class integraExternalServices : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback NotifyPlateFineOperationCompleted;
        
        private System.Threading.SendOrPostCallback NotifyPlateFineJSONOperationCompleted;
        
        private System.Threading.SendOrPostCallback NotifyPlateParkingOperationCompleted;
        
        private System.Threading.SendOrPostCallback NotifyPlateParkingJSONOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryPlateLastParkingOperationOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryPlateLastParkingOperationJSONOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryParkingOperationsOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryParkingOperationsJSONOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryFinePaymentsOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryFinePaymentsJSONOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryCouponOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryCouponJSONOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConfirmCouponOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConfirmCouponJSONOperationCompleted;
        
        private System.Threading.SendOrPostCallback NotifyCarEntryOperationCompleted;
        
        private System.Threading.SendOrPostCallback NotifyCarEntryJSONOperationCompleted;
        
        private System.Threading.SendOrPostCallback TryCarPaymentOperationCompleted;
        
        private System.Threading.SendOrPostCallback TryCarPaymentJSONOperationCompleted;
        
        private System.Threading.SendOrPostCallback NotifyCarExitOperationCompleted;
        
        private System.Threading.SendOrPostCallback NotifyCarExitJSONOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendPushWPNotificationsToOperationCompleted;
        
        private System.Threading.SendOrPostCallback NotifyTollPaymentOperationCompleted;
        
        private System.Threading.SendOrPostCallback NotifyTollPaymentJSONOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendPushAndroidNotificationsToOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryFinePaymentQuantityOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExternalticketPaymentParkingmeterOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryParkingOperationWithAmountStepsOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryUnParkingOperationOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertExternalParkingOperationInstallationTimeOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertExternalUnParkingOperationInstallationTimeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public integraExternalServices() {
            this.Url = global::integraMobile.ExternalWS.Properties.Settings.Default.integraMobile_ExternalWS_integraExternalServices_integraExternalServices;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event NotifyPlateFineCompletedEventHandler NotifyPlateFineCompleted;
        
        /// <remarks/>
        public event NotifyPlateFineJSONCompletedEventHandler NotifyPlateFineJSONCompleted;
        
        /// <remarks/>
        public event NotifyPlateParkingCompletedEventHandler NotifyPlateParkingCompleted;
        
        /// <remarks/>
        public event NotifyPlateParkingJSONCompletedEventHandler NotifyPlateParkingJSONCompleted;
        
        /// <remarks/>
        public event QueryPlateLastParkingOperationCompletedEventHandler QueryPlateLastParkingOperationCompleted;
        
        /// <remarks/>
        public event QueryPlateLastParkingOperationJSONCompletedEventHandler QueryPlateLastParkingOperationJSONCompleted;
        
        /// <remarks/>
        public event QueryParkingOperationsCompletedEventHandler QueryParkingOperationsCompleted;
        
        /// <remarks/>
        public event QueryParkingOperationsJSONCompletedEventHandler QueryParkingOperationsJSONCompleted;
        
        /// <remarks/>
        public event QueryFinePaymentsCompletedEventHandler QueryFinePaymentsCompleted;
        
        /// <remarks/>
        public event QueryFinePaymentsJSONCompletedEventHandler QueryFinePaymentsJSONCompleted;
        
        /// <remarks/>
        public event QueryCouponCompletedEventHandler QueryCouponCompleted;
        
        /// <remarks/>
        public event QueryCouponJSONCompletedEventHandler QueryCouponJSONCompleted;
        
        /// <remarks/>
        public event ConfirmCouponCompletedEventHandler ConfirmCouponCompleted;
        
        /// <remarks/>
        public event ConfirmCouponJSONCompletedEventHandler ConfirmCouponJSONCompleted;
        
        /// <remarks/>
        public event NotifyCarEntryCompletedEventHandler NotifyCarEntryCompleted;
        
        /// <remarks/>
        public event NotifyCarEntryJSONCompletedEventHandler NotifyCarEntryJSONCompleted;
        
        /// <remarks/>
        public event TryCarPaymentCompletedEventHandler TryCarPaymentCompleted;
        
        /// <remarks/>
        public event TryCarPaymentJSONCompletedEventHandler TryCarPaymentJSONCompleted;
        
        /// <remarks/>
        public event NotifyCarExitCompletedEventHandler NotifyCarExitCompleted;
        
        /// <remarks/>
        public event NotifyCarExitJSONCompletedEventHandler NotifyCarExitJSONCompleted;
        
        /// <remarks/>
        public event SendPushWPNotificationsToCompletedEventHandler SendPushWPNotificationsToCompleted;
        
        /// <remarks/>
        public event NotifyTollPaymentCompletedEventHandler NotifyTollPaymentCompleted;
        
        /// <remarks/>
        public event NotifyTollPaymentJSONCompletedEventHandler NotifyTollPaymentJSONCompleted;
        
        /// <remarks/>
        public event SendPushAndroidNotificationsToCompletedEventHandler SendPushAndroidNotificationsToCompleted;
        
        /// <remarks/>
        public event QueryFinePaymentQuantityCompletedEventHandler QueryFinePaymentQuantityCompleted;
        
        /// <remarks/>
        public event ExternalticketPaymentParkingmeterCompletedEventHandler ExternalticketPaymentParkingmeterCompleted;
        
        /// <remarks/>
        public event QueryParkingOperationWithAmountStepsCompletedEventHandler QueryParkingOperationWithAmountStepsCompleted;
        
        /// <remarks/>
        public event QueryUnParkingOperationCompletedEventHandler QueryUnParkingOperationCompleted;
        
        /// <remarks/>
        public event InsertExternalParkingOperationInstallationTimeCompletedEventHandler InsertExternalParkingOperationInstallationTimeCompleted;
        
        /// <remarks/>
        public event InsertExternalUnParkingOperationInstallationTimeCompletedEventHandler InsertExternalUnParkingOperationInstallationTimeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NotifyPlateFine", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string NotifyPlateFine(string xmlIn) {
            object[] results = this.Invoke("NotifyPlateFine", new object[] {
                        xmlIn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void NotifyPlateFineAsync(string xmlIn) {
            this.NotifyPlateFineAsync(xmlIn, null);
        }
        
        /// <remarks/>
        public void NotifyPlateFineAsync(string xmlIn, object userState) {
            if ((this.NotifyPlateFineOperationCompleted == null)) {
                this.NotifyPlateFineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNotifyPlateFineOperationCompleted);
            }
            this.InvokeAsync("NotifyPlateFine", new object[] {
                        xmlIn}, this.NotifyPlateFineOperationCompleted, userState);
        }
        
        private void OnNotifyPlateFineOperationCompleted(object arg) {
            if ((this.NotifyPlateFineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NotifyPlateFineCompleted(this, new NotifyPlateFineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NotifyPlateFineJSON", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string NotifyPlateFineJSON(string jsonIn) {
            object[] results = this.Invoke("NotifyPlateFineJSON", new object[] {
                        jsonIn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void NotifyPlateFineJSONAsync(string jsonIn) {
            this.NotifyPlateFineJSONAsync(jsonIn, null);
        }
        
        /// <remarks/>
        public void NotifyPlateFineJSONAsync(string jsonIn, object userState) {
            if ((this.NotifyPlateFineJSONOperationCompleted == null)) {
                this.NotifyPlateFineJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNotifyPlateFineJSONOperationCompleted);
            }
            this.InvokeAsync("NotifyPlateFineJSON", new object[] {
                        jsonIn}, this.NotifyPlateFineJSONOperationCompleted, userState);
        }
        
        private void OnNotifyPlateFineJSONOperationCompleted(object arg) {
            if ((this.NotifyPlateFineJSONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NotifyPlateFineJSONCompleted(this, new NotifyPlateFineJSONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NotifyPlateParking", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string NotifyPlateParking(string xmlIn) {
            object[] results = this.Invoke("NotifyPlateParking", new object[] {
                        xmlIn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void NotifyPlateParkingAsync(string xmlIn) {
            this.NotifyPlateParkingAsync(xmlIn, null);
        }
        
        /// <remarks/>
        public void NotifyPlateParkingAsync(string xmlIn, object userState) {
            if ((this.NotifyPlateParkingOperationCompleted == null)) {
                this.NotifyPlateParkingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNotifyPlateParkingOperationCompleted);
            }
            this.InvokeAsync("NotifyPlateParking", new object[] {
                        xmlIn}, this.NotifyPlateParkingOperationCompleted, userState);
        }
        
        private void OnNotifyPlateParkingOperationCompleted(object arg) {
            if ((this.NotifyPlateParkingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NotifyPlateParkingCompleted(this, new NotifyPlateParkingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NotifyPlateParkingJSON", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string NotifyPlateParkingJSON(string jsonIn) {
            object[] results = this.Invoke("NotifyPlateParkingJSON", new object[] {
                        jsonIn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void NotifyPlateParkingJSONAsync(string jsonIn) {
            this.NotifyPlateParkingJSONAsync(jsonIn, null);
        }
        
        /// <remarks/>
        public void NotifyPlateParkingJSONAsync(string jsonIn, object userState) {
            if ((this.NotifyPlateParkingJSONOperationCompleted == null)) {
                this.NotifyPlateParkingJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNotifyPlateParkingJSONOperationCompleted);
            }
            this.InvokeAsync("NotifyPlateParkingJSON", new object[] {
                        jsonIn}, this.NotifyPlateParkingJSONOperationCompleted, userState);
        }
        
        private void OnNotifyPlateParkingJSONOperationCompleted(object arg) {
            if ((this.NotifyPlateParkingJSONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NotifyPlateParkingJSONCompleted(this, new NotifyPlateParkingJSONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryPlateLastParkingOperation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string QueryPlateLastParkingOperation(string xmlIn) {
            object[] results = this.Invoke("QueryPlateLastParkingOperation", new object[] {
                        xmlIn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void QueryPlateLastParkingOperationAsync(string xmlIn) {
            this.QueryPlateLastParkingOperationAsync(xmlIn, null);
        }
        
        /// <remarks/>
        public void QueryPlateLastParkingOperationAsync(string xmlIn, object userState) {
            if ((this.QueryPlateLastParkingOperationOperationCompleted == null)) {
                this.QueryPlateLastParkingOperationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryPlateLastParkingOperationOperationCompleted);
            }
            this.InvokeAsync("QueryPlateLastParkingOperation", new object[] {
                        xmlIn}, this.QueryPlateLastParkingOperationOperationCompleted, userState);
        }
        
        private void OnQueryPlateLastParkingOperationOperationCompleted(object arg) {
            if ((this.QueryPlateLastParkingOperationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryPlateLastParkingOperationCompleted(this, new QueryPlateLastParkingOperationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryPlateLastParkingOperationJSON", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string QueryPlateLastParkingOperationJSON(string jsonIn) {
            object[] results = this.Invoke("QueryPlateLastParkingOperationJSON", new object[] {
                        jsonIn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void QueryPlateLastParkingOperationJSONAsync(string jsonIn) {
            this.QueryPlateLastParkingOperationJSONAsync(jsonIn, null);
        }
        
        /// <remarks/>
        public void QueryPlateLastParkingOperationJSONAsync(string jsonIn, object userState) {
            if ((this.QueryPlateLastParkingOperationJSONOperationCompleted == null)) {
                this.QueryPlateLastParkingOperationJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryPlateLastParkingOperationJSONOperationCompleted);
            }
            this.InvokeAsync("QueryPlateLastParkingOperationJSON", new object[] {
                        jsonIn}, this.QueryPlateLastParkingOperationJSONOperationCompleted, userState);
        }
        
        private void OnQueryPlateLastParkingOperationJSONOperationCompleted(object arg) {
            if ((this.QueryPlateLastParkingOperationJSONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryPlateLastParkingOperationJSONCompleted(this, new QueryPlateLastParkingOperationJSONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryParkingOperations", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string QueryParkingOperations(string xmlIn) {
            object[] results = this.Invoke("QueryParkingOperations", new object[] {
                        xmlIn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void QueryParkingOperationsAsync(string xmlIn) {
            this.QueryParkingOperationsAsync(xmlIn, null);
        }
        
        /// <remarks/>
        public void QueryParkingOperationsAsync(string xmlIn, object userState) {
            if ((this.QueryParkingOperationsOperationCompleted == null)) {
                this.QueryParkingOperationsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryParkingOperationsOperationCompleted);
            }
            this.InvokeAsync("QueryParkingOperations", new object[] {
                        xmlIn}, this.QueryParkingOperationsOperationCompleted, userState);
        }
        
        private void OnQueryParkingOperationsOperationCompleted(object arg) {
            if ((this.QueryParkingOperationsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryParkingOperationsCompleted(this, new QueryParkingOperationsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryParkingOperationsJSON", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string QueryParkingOperationsJSON(string jsonIn) {
            object[] results = this.Invoke("QueryParkingOperationsJSON", new object[] {
                        jsonIn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void QueryParkingOperationsJSONAsync(string jsonIn) {
            this.QueryParkingOperationsJSONAsync(jsonIn, null);
        }
        
        /// <remarks/>
        public void QueryParkingOperationsJSONAsync(string jsonIn, object userState) {
            if ((this.QueryParkingOperationsJSONOperationCompleted == null)) {
                this.QueryParkingOperationsJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryParkingOperationsJSONOperationCompleted);
            }
            this.InvokeAsync("QueryParkingOperationsJSON", new object[] {
                        jsonIn}, this.QueryParkingOperationsJSONOperationCompleted, userState);
        }
        
        private void OnQueryParkingOperationsJSONOperationCompleted(object arg) {
            if ((this.QueryParkingOperationsJSONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryParkingOperationsJSONCompleted(this, new QueryParkingOperationsJSONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryFinePayments", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string QueryFinePayments(string xmlIn) {
            object[] results = this.Invoke("QueryFinePayments", new object[] {
                        xmlIn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void QueryFinePaymentsAsync(string xmlIn) {
            this.QueryFinePaymentsAsync(xmlIn, null);
        }
        
        /// <remarks/>
        public void QueryFinePaymentsAsync(string xmlIn, object userState) {
            if ((this.QueryFinePaymentsOperationCompleted == null)) {
                this.QueryFinePaymentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryFinePaymentsOperationCompleted);
            }
            this.InvokeAsync("QueryFinePayments", new object[] {
                        xmlIn}, this.QueryFinePaymentsOperationCompleted, userState);
        }
        
        private void OnQueryFinePaymentsOperationCompleted(object arg) {
            if ((this.QueryFinePaymentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryFinePaymentsCompleted(this, new QueryFinePaymentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryFinePaymentsJSON", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string QueryFinePaymentsJSON(string jsonIn) {
            object[] results = this.Invoke("QueryFinePaymentsJSON", new object[] {
                        jsonIn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void QueryFinePaymentsJSONAsync(string jsonIn) {
            this.QueryFinePaymentsJSONAsync(jsonIn, null);
        }
        
        /// <remarks/>
        public void QueryFinePaymentsJSONAsync(string jsonIn, object userState) {
            if ((this.QueryFinePaymentsJSONOperationCompleted == null)) {
                this.QueryFinePaymentsJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryFinePaymentsJSONOperationCompleted);
            }
            this.InvokeAsync("QueryFinePaymentsJSON", new object[] {
                        jsonIn}, this.QueryFinePaymentsJSONOperationCompleted, userState);
        }
        
        private void OnQueryFinePaymentsJSONOperationCompleted(object arg) {
            if ((this.QueryFinePaymentsJSONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryFinePaymentsJSONCompleted(this, new QueryFinePaymentsJSONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryCoupon", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string QueryCoupon(string xmlIn) {
            object[] results = this.Invoke("QueryCoupon", new object[] {
                        xmlIn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void QueryCouponAsync(string xmlIn) {
            this.QueryCouponAsync(xmlIn, null);
        }
        
        /// <remarks/>
        public void QueryCouponAsync(string xmlIn, object userState) {
            if ((this.QueryCouponOperationCompleted == null)) {
                this.QueryCouponOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryCouponOperationCompleted);
            }
            this.InvokeAsync("QueryCoupon", new object[] {
                        xmlIn}, this.QueryCouponOperationCompleted, userState);
        }
        
        private void OnQueryCouponOperationCompleted(object arg) {
            if ((this.QueryCouponCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryCouponCompleted(this, new QueryCouponCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryCouponJSON", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string QueryCouponJSON(string jsonIn) {
            object[] results = this.Invoke("QueryCouponJSON", new object[] {
                        jsonIn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void QueryCouponJSONAsync(string jsonIn) {
            this.QueryCouponJSONAsync(jsonIn, null);
        }
        
        /// <remarks/>
        public void QueryCouponJSONAsync(string jsonIn, object userState) {
            if ((this.QueryCouponJSONOperationCompleted == null)) {
                this.QueryCouponJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryCouponJSONOperationCompleted);
            }
            this.InvokeAsync("QueryCouponJSON", new object[] {
                        jsonIn}, this.QueryCouponJSONOperationCompleted, userState);
        }
        
        private void OnQueryCouponJSONOperationCompleted(object arg) {
            if ((this.QueryCouponJSONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryCouponJSONCompleted(this, new QueryCouponJSONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConfirmCoupon", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConfirmCoupon(string xmlIn) {
            object[] results = this.Invoke("ConfirmCoupon", new object[] {
                        xmlIn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConfirmCouponAsync(string xmlIn) {
            this.ConfirmCouponAsync(xmlIn, null);
        }
        
        /// <remarks/>
        public void ConfirmCouponAsync(string xmlIn, object userState) {
            if ((this.ConfirmCouponOperationCompleted == null)) {
                this.ConfirmCouponOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConfirmCouponOperationCompleted);
            }
            this.InvokeAsync("ConfirmCoupon", new object[] {
                        xmlIn}, this.ConfirmCouponOperationCompleted, userState);
        }
        
        private void OnConfirmCouponOperationCompleted(object arg) {
            if ((this.ConfirmCouponCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConfirmCouponCompleted(this, new ConfirmCouponCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConfirmCouponJSON", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConfirmCouponJSON(string jsonIn) {
            object[] results = this.Invoke("ConfirmCouponJSON", new object[] {
                        jsonIn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConfirmCouponJSONAsync(string jsonIn) {
            this.ConfirmCouponJSONAsync(jsonIn, null);
        }
        
        /// <remarks/>
        public void ConfirmCouponJSONAsync(string jsonIn, object userState) {
            if ((this.ConfirmCouponJSONOperationCompleted == null)) {
                this.ConfirmCouponJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConfirmCouponJSONOperationCompleted);
            }
            this.InvokeAsync("ConfirmCouponJSON", new object[] {
                        jsonIn}, this.ConfirmCouponJSONOperationCompleted, userState);
        }
        
        private void OnConfirmCouponJSONOperationCompleted(object arg) {
            if ((this.ConfirmCouponJSONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConfirmCouponJSONCompleted(this, new ConfirmCouponJSONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NotifyCarEntry", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string NotifyCarEntry(string xmlIn) {
            object[] results = this.Invoke("NotifyCarEntry", new object[] {
                        xmlIn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void NotifyCarEntryAsync(string xmlIn) {
            this.NotifyCarEntryAsync(xmlIn, null);
        }
        
        /// <remarks/>
        public void NotifyCarEntryAsync(string xmlIn, object userState) {
            if ((this.NotifyCarEntryOperationCompleted == null)) {
                this.NotifyCarEntryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNotifyCarEntryOperationCompleted);
            }
            this.InvokeAsync("NotifyCarEntry", new object[] {
                        xmlIn}, this.NotifyCarEntryOperationCompleted, userState);
        }
        
        private void OnNotifyCarEntryOperationCompleted(object arg) {
            if ((this.NotifyCarEntryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NotifyCarEntryCompleted(this, new NotifyCarEntryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NotifyCarEntryJSON", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string NotifyCarEntryJSON(string jsonIn) {
            object[] results = this.Invoke("NotifyCarEntryJSON", new object[] {
                        jsonIn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void NotifyCarEntryJSONAsync(string jsonIn) {
            this.NotifyCarEntryJSONAsync(jsonIn, null);
        }
        
        /// <remarks/>
        public void NotifyCarEntryJSONAsync(string jsonIn, object userState) {
            if ((this.NotifyCarEntryJSONOperationCompleted == null)) {
                this.NotifyCarEntryJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNotifyCarEntryJSONOperationCompleted);
            }
            this.InvokeAsync("NotifyCarEntryJSON", new object[] {
                        jsonIn}, this.NotifyCarEntryJSONOperationCompleted, userState);
        }
        
        private void OnNotifyCarEntryJSONOperationCompleted(object arg) {
            if ((this.NotifyCarEntryJSONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NotifyCarEntryJSONCompleted(this, new NotifyCarEntryJSONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TryCarPayment", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TryCarPayment(string xmlIn) {
            object[] results = this.Invoke("TryCarPayment", new object[] {
                        xmlIn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TryCarPaymentAsync(string xmlIn) {
            this.TryCarPaymentAsync(xmlIn, null);
        }
        
        /// <remarks/>
        public void TryCarPaymentAsync(string xmlIn, object userState) {
            if ((this.TryCarPaymentOperationCompleted == null)) {
                this.TryCarPaymentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTryCarPaymentOperationCompleted);
            }
            this.InvokeAsync("TryCarPayment", new object[] {
                        xmlIn}, this.TryCarPaymentOperationCompleted, userState);
        }
        
        private void OnTryCarPaymentOperationCompleted(object arg) {
            if ((this.TryCarPaymentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TryCarPaymentCompleted(this, new TryCarPaymentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TryCarPaymentJSON", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TryCarPaymentJSON(string jsonIn) {
            object[] results = this.Invoke("TryCarPaymentJSON", new object[] {
                        jsonIn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TryCarPaymentJSONAsync(string jsonIn) {
            this.TryCarPaymentJSONAsync(jsonIn, null);
        }
        
        /// <remarks/>
        public void TryCarPaymentJSONAsync(string jsonIn, object userState) {
            if ((this.TryCarPaymentJSONOperationCompleted == null)) {
                this.TryCarPaymentJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTryCarPaymentJSONOperationCompleted);
            }
            this.InvokeAsync("TryCarPaymentJSON", new object[] {
                        jsonIn}, this.TryCarPaymentJSONOperationCompleted, userState);
        }
        
        private void OnTryCarPaymentJSONOperationCompleted(object arg) {
            if ((this.TryCarPaymentJSONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TryCarPaymentJSONCompleted(this, new TryCarPaymentJSONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NotifyCarExit", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string NotifyCarExit(string xmlIn) {
            object[] results = this.Invoke("NotifyCarExit", new object[] {
                        xmlIn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void NotifyCarExitAsync(string xmlIn) {
            this.NotifyCarExitAsync(xmlIn, null);
        }
        
        /// <remarks/>
        public void NotifyCarExitAsync(string xmlIn, object userState) {
            if ((this.NotifyCarExitOperationCompleted == null)) {
                this.NotifyCarExitOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNotifyCarExitOperationCompleted);
            }
            this.InvokeAsync("NotifyCarExit", new object[] {
                        xmlIn}, this.NotifyCarExitOperationCompleted, userState);
        }
        
        private void OnNotifyCarExitOperationCompleted(object arg) {
            if ((this.NotifyCarExitCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NotifyCarExitCompleted(this, new NotifyCarExitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NotifyCarExitJSON", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string NotifyCarExitJSON(string jsonIn) {
            object[] results = this.Invoke("NotifyCarExitJSON", new object[] {
                        jsonIn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void NotifyCarExitJSONAsync(string jsonIn) {
            this.NotifyCarExitJSONAsync(jsonIn, null);
        }
        
        /// <remarks/>
        public void NotifyCarExitJSONAsync(string jsonIn, object userState) {
            if ((this.NotifyCarExitJSONOperationCompleted == null)) {
                this.NotifyCarExitJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNotifyCarExitJSONOperationCompleted);
            }
            this.InvokeAsync("NotifyCarExitJSON", new object[] {
                        jsonIn}, this.NotifyCarExitJSONOperationCompleted, userState);
        }
        
        private void OnNotifyCarExitJSONOperationCompleted(object arg) {
            if ((this.NotifyCarExitJSONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NotifyCarExitJSONCompleted(this, new NotifyCarExitJSONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendPushWPNotificationsTo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SendPushWPNotificationsTo(string strUser, string strToastText1, string strToastText2, string strToastParam, string strTileTitle, int iTileCount, string strBackgroundImage) {
            object[] results = this.Invoke("SendPushWPNotificationsTo", new object[] {
                        strUser,
                        strToastText1,
                        strToastText2,
                        strToastParam,
                        strTileTitle,
                        iTileCount,
                        strBackgroundImage});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SendPushWPNotificationsToAsync(string strUser, string strToastText1, string strToastText2, string strToastParam, string strTileTitle, int iTileCount, string strBackgroundImage) {
            this.SendPushWPNotificationsToAsync(strUser, strToastText1, strToastText2, strToastParam, strTileTitle, iTileCount, strBackgroundImage, null);
        }
        
        /// <remarks/>
        public void SendPushWPNotificationsToAsync(string strUser, string strToastText1, string strToastText2, string strToastParam, string strTileTitle, int iTileCount, string strBackgroundImage, object userState) {
            if ((this.SendPushWPNotificationsToOperationCompleted == null)) {
                this.SendPushWPNotificationsToOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendPushWPNotificationsToOperationCompleted);
            }
            this.InvokeAsync("SendPushWPNotificationsTo", new object[] {
                        strUser,
                        strToastText1,
                        strToastText2,
                        strToastParam,
                        strTileTitle,
                        iTileCount,
                        strBackgroundImage}, this.SendPushWPNotificationsToOperationCompleted, userState);
        }
        
        private void OnSendPushWPNotificationsToOperationCompleted(object arg) {
            if ((this.SendPushWPNotificationsToCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendPushWPNotificationsToCompleted(this, new SendPushWPNotificationsToCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NotifyTollPayment", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string NotifyTollPayment(string xmlIn) {
            object[] results = this.Invoke("NotifyTollPayment", new object[] {
                        xmlIn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void NotifyTollPaymentAsync(string xmlIn) {
            this.NotifyTollPaymentAsync(xmlIn, null);
        }
        
        /// <remarks/>
        public void NotifyTollPaymentAsync(string xmlIn, object userState) {
            if ((this.NotifyTollPaymentOperationCompleted == null)) {
                this.NotifyTollPaymentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNotifyTollPaymentOperationCompleted);
            }
            this.InvokeAsync("NotifyTollPayment", new object[] {
                        xmlIn}, this.NotifyTollPaymentOperationCompleted, userState);
        }
        
        private void OnNotifyTollPaymentOperationCompleted(object arg) {
            if ((this.NotifyTollPaymentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NotifyTollPaymentCompleted(this, new NotifyTollPaymentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NotifyTollPaymentJSON", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string NotifyTollPaymentJSON(string jsonIn) {
            object[] results = this.Invoke("NotifyTollPaymentJSON", new object[] {
                        jsonIn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void NotifyTollPaymentJSONAsync(string jsonIn) {
            this.NotifyTollPaymentJSONAsync(jsonIn, null);
        }
        
        /// <remarks/>
        public void NotifyTollPaymentJSONAsync(string jsonIn, object userState) {
            if ((this.NotifyTollPaymentJSONOperationCompleted == null)) {
                this.NotifyTollPaymentJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNotifyTollPaymentJSONOperationCompleted);
            }
            this.InvokeAsync("NotifyTollPaymentJSON", new object[] {
                        jsonIn}, this.NotifyTollPaymentJSONOperationCompleted, userState);
        }
        
        private void OnNotifyTollPaymentJSONOperationCompleted(object arg) {
            if ((this.NotifyTollPaymentJSONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NotifyTollPaymentJSONCompleted(this, new NotifyTollPaymentJSONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendPushAndroidNotificationsTo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SendPushAndroidNotificationsTo(string strUser, string strAndroidRawData) {
            object[] results = this.Invoke("SendPushAndroidNotificationsTo", new object[] {
                        strUser,
                        strAndroidRawData});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SendPushAndroidNotificationsToAsync(string strUser, string strAndroidRawData) {
            this.SendPushAndroidNotificationsToAsync(strUser, strAndroidRawData, null);
        }
        
        /// <remarks/>
        public void SendPushAndroidNotificationsToAsync(string strUser, string strAndroidRawData, object userState) {
            if ((this.SendPushAndroidNotificationsToOperationCompleted == null)) {
                this.SendPushAndroidNotificationsToOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendPushAndroidNotificationsToOperationCompleted);
            }
            this.InvokeAsync("SendPushAndroidNotificationsTo", new object[] {
                        strUser,
                        strAndroidRawData}, this.SendPushAndroidNotificationsToOperationCompleted, userState);
        }
        
        private void OnSendPushAndroidNotificationsToOperationCompleted(object arg) {
            if ((this.SendPushAndroidNotificationsToCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendPushAndroidNotificationsToCompleted(this, new SendPushAndroidNotificationsToCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryFinePaymentQuantity", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string QueryFinePaymentQuantity(string xmlIn) {
            object[] results = this.Invoke("QueryFinePaymentQuantity", new object[] {
                        xmlIn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void QueryFinePaymentQuantityAsync(string xmlIn) {
            this.QueryFinePaymentQuantityAsync(xmlIn, null);
        }
        
        /// <remarks/>
        public void QueryFinePaymentQuantityAsync(string xmlIn, object userState) {
            if ((this.QueryFinePaymentQuantityOperationCompleted == null)) {
                this.QueryFinePaymentQuantityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryFinePaymentQuantityOperationCompleted);
            }
            this.InvokeAsync("QueryFinePaymentQuantity", new object[] {
                        xmlIn}, this.QueryFinePaymentQuantityOperationCompleted, userState);
        }
        
        private void OnQueryFinePaymentQuantityOperationCompleted(object arg) {
            if ((this.QueryFinePaymentQuantityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryFinePaymentQuantityCompleted(this, new QueryFinePaymentQuantityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ExternalticketPaymentParkingmeter", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ExternalticketPaymentParkingmeter(string xmlIn) {
            object[] results = this.Invoke("ExternalticketPaymentParkingmeter", new object[] {
                        xmlIn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ExternalticketPaymentParkingmeterAsync(string xmlIn) {
            this.ExternalticketPaymentParkingmeterAsync(xmlIn, null);
        }
        
        /// <remarks/>
        public void ExternalticketPaymentParkingmeterAsync(string xmlIn, object userState) {
            if ((this.ExternalticketPaymentParkingmeterOperationCompleted == null)) {
                this.ExternalticketPaymentParkingmeterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExternalticketPaymentParkingmeterOperationCompleted);
            }
            this.InvokeAsync("ExternalticketPaymentParkingmeter", new object[] {
                        xmlIn}, this.ExternalticketPaymentParkingmeterOperationCompleted, userState);
        }
        
        private void OnExternalticketPaymentParkingmeterOperationCompleted(object arg) {
            if ((this.ExternalticketPaymentParkingmeterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExternalticketPaymentParkingmeterCompleted(this, new ExternalticketPaymentParkingmeterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryParkingOperationWithAmountSteps", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string QueryParkingOperationWithAmountSteps(string xmlIn) {
            object[] results = this.Invoke("QueryParkingOperationWithAmountSteps", new object[] {
                        xmlIn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void QueryParkingOperationWithAmountStepsAsync(string xmlIn) {
            this.QueryParkingOperationWithAmountStepsAsync(xmlIn, null);
        }
        
        /// <remarks/>
        public void QueryParkingOperationWithAmountStepsAsync(string xmlIn, object userState) {
            if ((this.QueryParkingOperationWithAmountStepsOperationCompleted == null)) {
                this.QueryParkingOperationWithAmountStepsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryParkingOperationWithAmountStepsOperationCompleted);
            }
            this.InvokeAsync("QueryParkingOperationWithAmountSteps", new object[] {
                        xmlIn}, this.QueryParkingOperationWithAmountStepsOperationCompleted, userState);
        }
        
        private void OnQueryParkingOperationWithAmountStepsOperationCompleted(object arg) {
            if ((this.QueryParkingOperationWithAmountStepsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryParkingOperationWithAmountStepsCompleted(this, new QueryParkingOperationWithAmountStepsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryUnParkingOperation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string QueryUnParkingOperation(string xmlIn) {
            object[] results = this.Invoke("QueryUnParkingOperation", new object[] {
                        xmlIn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void QueryUnParkingOperationAsync(string xmlIn) {
            this.QueryUnParkingOperationAsync(xmlIn, null);
        }
        
        /// <remarks/>
        public void QueryUnParkingOperationAsync(string xmlIn, object userState) {
            if ((this.QueryUnParkingOperationOperationCompleted == null)) {
                this.QueryUnParkingOperationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryUnParkingOperationOperationCompleted);
            }
            this.InvokeAsync("QueryUnParkingOperation", new object[] {
                        xmlIn}, this.QueryUnParkingOperationOperationCompleted, userState);
        }
        
        private void OnQueryUnParkingOperationOperationCompleted(object arg) {
            if ((this.QueryUnParkingOperationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryUnParkingOperationCompleted(this, new QueryUnParkingOperationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertExternalParkingOperationInstallationTime", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InsertExternalParkingOperationInstallationTime(string xmlIn) {
            object[] results = this.Invoke("InsertExternalParkingOperationInstallationTime", new object[] {
                        xmlIn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void InsertExternalParkingOperationInstallationTimeAsync(string xmlIn) {
            this.InsertExternalParkingOperationInstallationTimeAsync(xmlIn, null);
        }
        
        /// <remarks/>
        public void InsertExternalParkingOperationInstallationTimeAsync(string xmlIn, object userState) {
            if ((this.InsertExternalParkingOperationInstallationTimeOperationCompleted == null)) {
                this.InsertExternalParkingOperationInstallationTimeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertExternalParkingOperationInstallationTimeOperationCompleted);
            }
            this.InvokeAsync("InsertExternalParkingOperationInstallationTime", new object[] {
                        xmlIn}, this.InsertExternalParkingOperationInstallationTimeOperationCompleted, userState);
        }
        
        private void OnInsertExternalParkingOperationInstallationTimeOperationCompleted(object arg) {
            if ((this.InsertExternalParkingOperationInstallationTimeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertExternalParkingOperationInstallationTimeCompleted(this, new InsertExternalParkingOperationInstallationTimeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertExternalUnParkingOperationInstallationTime", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InsertExternalUnParkingOperationInstallationTime(string xmlIn) {
            object[] results = this.Invoke("InsertExternalUnParkingOperationInstallationTime", new object[] {
                        xmlIn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void InsertExternalUnParkingOperationInstallationTimeAsync(string xmlIn) {
            this.InsertExternalUnParkingOperationInstallationTimeAsync(xmlIn, null);
        }
        
        /// <remarks/>
        public void InsertExternalUnParkingOperationInstallationTimeAsync(string xmlIn, object userState) {
            if ((this.InsertExternalUnParkingOperationInstallationTimeOperationCompleted == null)) {
                this.InsertExternalUnParkingOperationInstallationTimeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertExternalUnParkingOperationInstallationTimeOperationCompleted);
            }
            this.InvokeAsync("InsertExternalUnParkingOperationInstallationTime", new object[] {
                        xmlIn}, this.InsertExternalUnParkingOperationInstallationTimeOperationCompleted, userState);
        }
        
        private void OnInsertExternalUnParkingOperationInstallationTimeOperationCompleted(object arg) {
            if ((this.InsertExternalUnParkingOperationInstallationTimeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertExternalUnParkingOperationInstallationTimeCompleted(this, new InsertExternalUnParkingOperationInstallationTimeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void NotifyPlateFineCompletedEventHandler(object sender, NotifyPlateFineCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NotifyPlateFineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NotifyPlateFineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void NotifyPlateFineJSONCompletedEventHandler(object sender, NotifyPlateFineJSONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NotifyPlateFineJSONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NotifyPlateFineJSONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void NotifyPlateParkingCompletedEventHandler(object sender, NotifyPlateParkingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NotifyPlateParkingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NotifyPlateParkingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void NotifyPlateParkingJSONCompletedEventHandler(object sender, NotifyPlateParkingJSONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NotifyPlateParkingJSONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NotifyPlateParkingJSONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void QueryPlateLastParkingOperationCompletedEventHandler(object sender, QueryPlateLastParkingOperationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryPlateLastParkingOperationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryPlateLastParkingOperationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void QueryPlateLastParkingOperationJSONCompletedEventHandler(object sender, QueryPlateLastParkingOperationJSONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryPlateLastParkingOperationJSONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryPlateLastParkingOperationJSONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void QueryParkingOperationsCompletedEventHandler(object sender, QueryParkingOperationsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryParkingOperationsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryParkingOperationsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void QueryParkingOperationsJSONCompletedEventHandler(object sender, QueryParkingOperationsJSONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryParkingOperationsJSONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryParkingOperationsJSONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void QueryFinePaymentsCompletedEventHandler(object sender, QueryFinePaymentsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryFinePaymentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryFinePaymentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void QueryFinePaymentsJSONCompletedEventHandler(object sender, QueryFinePaymentsJSONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryFinePaymentsJSONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryFinePaymentsJSONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void QueryCouponCompletedEventHandler(object sender, QueryCouponCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryCouponCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryCouponCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void QueryCouponJSONCompletedEventHandler(object sender, QueryCouponJSONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryCouponJSONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryCouponJSONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ConfirmCouponCompletedEventHandler(object sender, ConfirmCouponCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConfirmCouponCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConfirmCouponCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ConfirmCouponJSONCompletedEventHandler(object sender, ConfirmCouponJSONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConfirmCouponJSONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConfirmCouponJSONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void NotifyCarEntryCompletedEventHandler(object sender, NotifyCarEntryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NotifyCarEntryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NotifyCarEntryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void NotifyCarEntryJSONCompletedEventHandler(object sender, NotifyCarEntryJSONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NotifyCarEntryJSONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NotifyCarEntryJSONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void TryCarPaymentCompletedEventHandler(object sender, TryCarPaymentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TryCarPaymentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TryCarPaymentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void TryCarPaymentJSONCompletedEventHandler(object sender, TryCarPaymentJSONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TryCarPaymentJSONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TryCarPaymentJSONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void NotifyCarExitCompletedEventHandler(object sender, NotifyCarExitCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NotifyCarExitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NotifyCarExitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void NotifyCarExitJSONCompletedEventHandler(object sender, NotifyCarExitJSONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NotifyCarExitJSONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NotifyCarExitJSONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void SendPushWPNotificationsToCompletedEventHandler(object sender, SendPushWPNotificationsToCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendPushWPNotificationsToCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendPushWPNotificationsToCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void NotifyTollPaymentCompletedEventHandler(object sender, NotifyTollPaymentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NotifyTollPaymentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NotifyTollPaymentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void NotifyTollPaymentJSONCompletedEventHandler(object sender, NotifyTollPaymentJSONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NotifyTollPaymentJSONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NotifyTollPaymentJSONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void SendPushAndroidNotificationsToCompletedEventHandler(object sender, SendPushAndroidNotificationsToCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendPushAndroidNotificationsToCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendPushAndroidNotificationsToCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void QueryFinePaymentQuantityCompletedEventHandler(object sender, QueryFinePaymentQuantityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryFinePaymentQuantityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryFinePaymentQuantityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ExternalticketPaymentParkingmeterCompletedEventHandler(object sender, ExternalticketPaymentParkingmeterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExternalticketPaymentParkingmeterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExternalticketPaymentParkingmeterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void QueryParkingOperationWithAmountStepsCompletedEventHandler(object sender, QueryParkingOperationWithAmountStepsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryParkingOperationWithAmountStepsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryParkingOperationWithAmountStepsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void QueryUnParkingOperationCompletedEventHandler(object sender, QueryUnParkingOperationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryUnParkingOperationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryUnParkingOperationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void InsertExternalParkingOperationInstallationTimeCompletedEventHandler(object sender, InsertExternalParkingOperationInstallationTimeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertExternalParkingOperationInstallationTimeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertExternalParkingOperationInstallationTimeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void InsertExternalUnParkingOperationInstallationTimeCompletedEventHandler(object sender, InsertExternalUnParkingOperationInstallationTimeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertExternalUnParkingOperationInstallationTimeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertExternalUnParkingOperationInstallationTimeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591