//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace integraMobile.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("integraMobile.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha producido un error en la activación de su cuenta, contacte con soporte en el teléfono de la OTA: 944-XXX-XXX o por correo electrónico a: xxxxxx@xxxxxx.com.
        /// </summary>
        public static string Activate_Account_Message1 {
            get {
                return ResourceManager.GetString("Activate_Account_Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activación Errónea.
        /// </summary>
        public static string ActivateAccount_Title {
            get {
                return ResourceManager.GetString("ActivateAccount_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su cuenta de usuario ha sido activada con éxito, ya puede iniciar sesión y utilizar BILBAOPARK..
        /// </summary>
        public static string ActivateAccountSuccess_Message1 {
            get {
                return ResourceManager.GetString("ActivateAccountSuccess_Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activación correcta.
        /// </summary>
        public static string ActivateAccountSuccess_Title {
            get {
                return ResourceManager.GetString("ActivateAccountSuccess_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        public static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar.
        /// </summary>
        public static string Button_Send {
            get {
                return ResourceManager.GetString("Button_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código de activación ya ha sido usado.
        /// </summary>
        public static string ErrMsg_ActivationCodeAlreadyUsed {
            get {
                return ResourceManager.GetString("ErrMsg_ActivationCodeAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código de activación ha expirado.
        /// </summary>
        public static string ErrMsg_ActivationCodeExpired_2 {
            get {
                return ResourceManager.GetString("ErrMsg_ActivationCodeExpired_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La url de activación es incorrecta.
        /// </summary>
        public static string ErrMsg_ActivationURLIncorrect {
            get {
                return ResourceManager.GetString("ErrMsg_ActivationURLIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La longitud máxima del campo {0} es {1}.
        /// </summary>
        public static string ErrorsMsg_InvalidLengthWithMinimum {
            get {
                return ResourceManager.GetString("ErrorsMsg_InvalidLengthWithMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las contraseñas deben coincidir.
        /// </summary>
        public static string ErrorsMsg_PasswordsMustMatch {
            get {
                return ResourceManager.GetString("ErrorsMsg_PasswordsMustMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo {0} es obligatario.
        /// </summary>
        public static string ErrorsMsg_RequiredField {
            get {
                return ResourceManager.GetString("ErrorsMsg_RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirme la nueva contraseña:.
        /// </summary>
        public static string ForgotPassword_ConfirmPassword {
            get {
                return ResourceManager.GetString("ForgotPassword_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para cambiar la contraseña de {0},debe introducir la nueva contraseña..
        /// </summary>
        public static string ForgotPassword_Message1 {
            get {
                return ResourceManager.GetString("ForgotPassword_Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, introduzca su nueva contraseña:.
        /// </summary>
        public static string ForgotPassword_Message2 {
            get {
                return ResourceManager.GetString("ForgotPassword_Message2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva Contraseña:.
        /// </summary>
        public static string ForgotPassword_Password {
            get {
                return ResourceManager.GetString("ForgotPassword_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar Contraseña.
        /// </summary>
        public static string ForgotPassword_Title {
            get {
                return ResourceManager.GetString("ForgotPassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Repita la contraseña.
        /// </summary>
        public static string ForgotPassword_WriteYourConfirmPassword {
            get {
                return ResourceManager.GetString("ForgotPassword_WriteYourConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Min.- {0} Max {1} caracteres.
        /// </summary>
        public static string ForgotPassword_WriteYourPassword {
            get {
                return ResourceManager.GetString("ForgotPassword_WriteYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su contraseña se cambió correctamente..
        /// </summary>
        public static string ForgotPasswordConfirmation_Message1 {
            get {
                return ResourceManager.GetString("ForgotPasswordConfirmation_Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña cambiada correctamente.
        /// </summary>
        public static string ForgotPasswordConfirmation_Title {
            get {
                return ResourceManager.GetString("ForgotPasswordConfirmation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector Azul.
        /// </summary>
        public static string Sector_60001 {
            get {
                return ResourceManager.GetString("Sector_60001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector Verde.
        /// </summary>
        public static string Sector_60002 {
            get {
                return ResourceManager.GetString("Sector_60002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector Azul.
        /// </summary>
        public static string Sector_60003 {
            get {
                return ResourceManager.GetString("Sector_60003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector Verde.
        /// </summary>
        public static string Sector_60004 {
            get {
                return ResourceManager.GetString("Sector_60004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector Azul.
        /// </summary>
        public static string Sector_60005 {
            get {
                return ResourceManager.GetString("Sector_60005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector Verde.
        /// </summary>
        public static string Sector_60006 {
            get {
                return ResourceManager.GetString("Sector_60006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector Azul.
        /// </summary>
        public static string Sector_60007 {
            get {
                return ResourceManager.GetString("Sector_60007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector Verde.
        /// </summary>
        public static string Sector_60008 {
            get {
                return ResourceManager.GetString("Sector_60008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector Azul.
        /// </summary>
        public static string Sector_60009 {
            get {
                return ResourceManager.GetString("Sector_60009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector Verde.
        /// </summary>
        public static string Sector_60010 {
            get {
                return ResourceManager.GetString("Sector_60010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector Azul.
        /// </summary>
        public static string Sector_60011 {
            get {
                return ResourceManager.GetString("Sector_60011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector Verde.
        /// </summary>
        public static string Sector_60012 {
            get {
                return ResourceManager.GetString("Sector_60012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector Azul.
        /// </summary>
        public static string Sector_60013 {
            get {
                return ResourceManager.GetString("Sector_60013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector Verde.
        /// </summary>
        public static string Sector_60014 {
            get {
                return ResourceManager.GetString("Sector_60014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector Azul.
        /// </summary>
        public static string Sector_60015 {
            get {
                return ResourceManager.GetString("Sector_60015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector Verde.
        /// </summary>
        public static string Sector_60016 {
            get {
                return ResourceManager.GetString("Sector_60016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector Azul.
        /// </summary>
        public static string Sector_60017 {
            get {
                return ResourceManager.GetString("Sector_60017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector Verde.
        /// </summary>
        public static string Sector_60018 {
            get {
                return ResourceManager.GetString("Sector_60018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector Azul.
        /// </summary>
        public static string Sector_60019 {
            get {
                return ResourceManager.GetString("Sector_60019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector Verde.
        /// </summary>
        public static string Sector_60020 {
            get {
                return ResourceManager.GetString("Sector_60020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector Azul.
        /// </summary>
        public static string Sector_60021 {
            get {
                return ResourceManager.GetString("Sector_60021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector Verde.
        /// </summary>
        public static string Sector_60022 {
            get {
                return ResourceManager.GetString("Sector_60022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector Azul.
        /// </summary>
        public static string Sector_60023 {
            get {
                return ResourceManager.GetString("Sector_60023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector Verde.
        /// </summary>
        public static string Sector_60024 {
            get {
                return ResourceManager.GetString("Sector_60024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector Azul.
        /// </summary>
        public static string Sector_60027 {
            get {
                return ResourceManager.GetString("Sector_60027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector Verde.
        /// </summary>
        public static string Sector_60028 {
            get {
                return ResourceManager.GetString("Sector_60028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector Verde L.
        /// </summary>
        public static string Sector_60029 {
            get {
                return ResourceManager.GetString("Sector_60029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01 - Abando.
        /// </summary>
        public static string Zone_60001 {
            get {
                return ResourceManager.GetString("Zone_60001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01 - Abando.
        /// </summary>
        public static string Zone_60002 {
            get {
                return ResourceManager.GetString("Zone_60002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 02 - Indautxu A.
        /// </summary>
        public static string Zone_60003 {
            get {
                return ResourceManager.GetString("Zone_60003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 02 - Indautxu A.
        /// </summary>
        public static string Zone_60004 {
            get {
                return ResourceManager.GetString("Zone_60004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 03 - Indautxu B.
        /// </summary>
        public static string Zone_60005 {
            get {
                return ResourceManager.GetString("Zone_60005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 03 - Indautxu B.
        /// </summary>
        public static string Zone_60006 {
            get {
                return ResourceManager.GetString("Zone_60006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 04 - Ametzola.
        /// </summary>
        public static string Zone_60007 {
            get {
                return ResourceManager.GetString("Zone_60007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 04 - Ametzola.
        /// </summary>
        public static string Zone_60008 {
            get {
                return ResourceManager.GetString("Zone_60008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 05 - Basurtu.
        /// </summary>
        public static string Zone_60009 {
            get {
                return ResourceManager.GetString("Zone_60009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 05 - Basurtu.
        /// </summary>
        public static string Zone_60010 {
            get {
                return ResourceManager.GetString("Zone_60010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 - Errekaldeberri.
        /// </summary>
        public static string Zone_60011 {
            get {
                return ResourceManager.GetString("Zone_60011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 - Errekaldeberri.
        /// </summary>
        public static string Zone_60012 {
            get {
                return ResourceManager.GetString("Zone_60012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 07 - Iralabarri.
        /// </summary>
        public static string Zone_60013 {
            get {
                return ResourceManager.GetString("Zone_60013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 07 - Iralabarri.
        /// </summary>
        public static string Zone_60014 {
            get {
                return ResourceManager.GetString("Zone_60014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 08 - Deustu.
        /// </summary>
        public static string Zone_60015 {
            get {
                return ResourceManager.GetString("Zone_60015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 08 - Deustu.
        /// </summary>
        public static string Zone_60016 {
            get {
                return ResourceManager.GetString("Zone_60016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9 - Castaños-Matiko.
        /// </summary>
        public static string Zone_60017 {
            get {
                return ResourceManager.GetString("Zone_60017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9 - Castaños-Matiko.
        /// </summary>
        public static string Zone_60018 {
            get {
                return ResourceManager.GetString("Zone_60018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 - Casco Viejo.
        /// </summary>
        public static string Zone_60019 {
            get {
                return ResourceManager.GetString("Zone_60019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 - Casco Viejo.
        /// </summary>
        public static string Zone_60020 {
            get {
                return ResourceManager.GetString("Zone_60020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10A - Begoña.
        /// </summary>
        public static string Zone_60021 {
            get {
                return ResourceManager.GetString("Zone_60021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10A - Begoña.
        /// </summary>
        public static string Zone_60022 {
            get {
                return ResourceManager.GetString("Zone_60022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11 - Santutxu.
        /// </summary>
        public static string Zone_60023 {
            get {
                return ResourceManager.GetString("Zone_60023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11 - Santutxu.
        /// </summary>
        public static string Zone_60024 {
            get {
                return ResourceManager.GetString("Zone_60024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12 - Ibaiondo.
        /// </summary>
        public static string Zone_60027 {
            get {
                return ResourceManager.GetString("Zone_60027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12 - Ibaiondo.
        /// </summary>
        public static string Zone_60028 {
            get {
                return ResourceManager.GetString("Zone_60028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12 - Ibaiondo.
        /// </summary>
        public static string Zone_60029 {
            get {
                return ResourceManager.GetString("Zone_60029", resourceCulture);
            }
        }
    }
}
