//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace integraMobile.ExternalWS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:41858/TariffComputer.asmx")]
        public string integraMobile_ExternalWS_StandardParkingWS_TariffComputerWS {
            get {
                return ((string)(this["integraMobile_ExternalWS_StandardParkingWS_TariffComputerWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://esixvyewb01t/parquimetrosWSVS2012/framework/ticket.asmx")]
        public string integraMobile_ExternalWS_EysaThirdPartyConfirmParkWS_Ticket {
            get {
                return ((string)(this["integraMobile_ExternalWS_EysaThirdPartyConfirmParkWS_Ticket"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://esdcvyewb02p/parquimetrosWS/framework/anulaciones.asmx")]
        public string integraMobile_ExternalWS_EysaThirdPartyFineWS_Anulaciones {
            get {
                return ((string)(this["integraMobile_ExternalWS_EysaThirdPartyFineWS_Anulaciones"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://demo.sales.gtechna.net/officercc-qa-ipark/ws/PayByPhoneOperation")]
        public string integraMobile_ExternalWS_gTechnaThirdPartyFineWS_PayByPhoneOperationService {
            get {
                return ((string)(this["integraMobile_ExternalWS_gTechnaThirdPartyFineWS_PayByPhoneOperationService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.3.91:8080/officercc-spaq/services/ParkingRightsListener")]
        public string integraMobile_ExternalWS_gTechnaThirdPartyParkingConfirmWS_MESParkingRightsSOAPFacadeService {
            get {
                return ((string)(this["integraMobile_ExternalWS_gTechnaThirdPartyParkingConfirmWS_MESParkingRightsSOAPFa" +
                    "cadeService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://eysaIP.eysanet.com/parquimetrosWS/framework/tarifas.asmx")]
        public string integraMobile_ExternalWS_EysaThirdPartyParkWS_Tarifas {
            get {
                return ((string)(this["integraMobile_ExternalWS_EysaThirdPartyParkWS_Tarifas"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://80.28.251.76:2424/InterfazPublicaWS/InterfazPublicaWebService.asmx")]
        public string integraMobile_ExternalWS_MeyparThirdPartyOffstreetWS_InterfazPublicaWebService {
            get {
                return ((string)(this["integraMobile_ExternalWS_MeyparThirdPartyOffstreetWS_InterfazPublicaWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.pagatelia.com/apipayments/ApiPayment.svc")]
        public string integraMobile_ExternalWS_PagateliaWS_ApiPayment {
            get {
                return ((string)(this["integraMobile_ExternalWS_PagateliaWS_ApiPayment"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nexus.meypar.com/PreProd/TariffComputerBilbo.WS/PIC_WS.asmx")]
        public string integraMobile_ExternalWS_MeyparPICWS_PIC_WS {
            get {
                return ((string)(this["integraMobile_ExternalWS_MeyparPICWS_PIC_WS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/integraMobile.WS_Bilbao/integraExternalServices.asmx")]
        public string integraMobile_ExternalWS_integraExternalServices_integraExternalServices {
            get {
                return ((string)(this["integraMobile_ExternalWS_integraExternalServices_integraExternalServices"]));
            }
        }
    }
}
