//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18051.
// 
#pragma warning disable 1591

namespace TestExternalWebServices.com.eysamobile.www {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="integraExternalServicesSoap", Namespace="http://tempuri.org/")]
    public partial class integraExternalServices : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback NotifyPlateFineOperationCompleted;
        
        private System.Threading.SendOrPostCallback NotifyPlateFineJSONOperationCompleted;
        
        private System.Threading.SendOrPostCallback NotifyPlateParkingOperationCompleted;
        
        private System.Threading.SendOrPostCallback NotifyPlateParkingJSONOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendPushWPNotificationsToOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendPushAndroidNotificationsToOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public integraExternalServices() {
            this.Url = global::TestExternalWebServices.Properties.Settings.Default.TestExternalWebServices_com_eysamobile_www_integraExternalServices;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event NotifyPlateFineCompletedEventHandler NotifyPlateFineCompleted;
        
        /// <remarks/>
        public event NotifyPlateFineJSONCompletedEventHandler NotifyPlateFineJSONCompleted;
        
        /// <remarks/>
        public event NotifyPlateParkingCompletedEventHandler NotifyPlateParkingCompleted;
        
        /// <remarks/>
        public event NotifyPlateParkingJSONCompletedEventHandler NotifyPlateParkingJSONCompleted;
        
        /// <remarks/>
        public event SendPushWPNotificationsToCompletedEventHandler SendPushWPNotificationsToCompleted;
        
        /// <remarks/>
        public event SendPushAndroidNotificationsToCompletedEventHandler SendPushAndroidNotificationsToCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NotifyPlateFine", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string NotifyPlateFine(string xmlIn) {
            object[] results = this.Invoke("NotifyPlateFine", new object[] {
                        xmlIn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void NotifyPlateFineAsync(string xmlIn) {
            this.NotifyPlateFineAsync(xmlIn, null);
        }
        
        /// <remarks/>
        public void NotifyPlateFineAsync(string xmlIn, object userState) {
            if ((this.NotifyPlateFineOperationCompleted == null)) {
                this.NotifyPlateFineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNotifyPlateFineOperationCompleted);
            }
            this.InvokeAsync("NotifyPlateFine", new object[] {
                        xmlIn}, this.NotifyPlateFineOperationCompleted, userState);
        }
        
        private void OnNotifyPlateFineOperationCompleted(object arg) {
            if ((this.NotifyPlateFineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NotifyPlateFineCompleted(this, new NotifyPlateFineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NotifyPlateFineJSON", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string NotifyPlateFineJSON(string jsonIn) {
            object[] results = this.Invoke("NotifyPlateFineJSON", new object[] {
                        jsonIn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void NotifyPlateFineJSONAsync(string jsonIn) {
            this.NotifyPlateFineJSONAsync(jsonIn, null);
        }
        
        /// <remarks/>
        public void NotifyPlateFineJSONAsync(string jsonIn, object userState) {
            if ((this.NotifyPlateFineJSONOperationCompleted == null)) {
                this.NotifyPlateFineJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNotifyPlateFineJSONOperationCompleted);
            }
            this.InvokeAsync("NotifyPlateFineJSON", new object[] {
                        jsonIn}, this.NotifyPlateFineJSONOperationCompleted, userState);
        }
        
        private void OnNotifyPlateFineJSONOperationCompleted(object arg) {
            if ((this.NotifyPlateFineJSONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NotifyPlateFineJSONCompleted(this, new NotifyPlateFineJSONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NotifyPlateParking", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string NotifyPlateParking(string xmlIn) {
            object[] results = this.Invoke("NotifyPlateParking", new object[] {
                        xmlIn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void NotifyPlateParkingAsync(string xmlIn) {
            this.NotifyPlateParkingAsync(xmlIn, null);
        }
        
        /// <remarks/>
        public void NotifyPlateParkingAsync(string xmlIn, object userState) {
            if ((this.NotifyPlateParkingOperationCompleted == null)) {
                this.NotifyPlateParkingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNotifyPlateParkingOperationCompleted);
            }
            this.InvokeAsync("NotifyPlateParking", new object[] {
                        xmlIn}, this.NotifyPlateParkingOperationCompleted, userState);
        }
        
        private void OnNotifyPlateParkingOperationCompleted(object arg) {
            if ((this.NotifyPlateParkingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NotifyPlateParkingCompleted(this, new NotifyPlateParkingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NotifyPlateParkingJSON", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string NotifyPlateParkingJSON(string jsonIn) {
            object[] results = this.Invoke("NotifyPlateParkingJSON", new object[] {
                        jsonIn});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void NotifyPlateParkingJSONAsync(string jsonIn) {
            this.NotifyPlateParkingJSONAsync(jsonIn, null);
        }
        
        /// <remarks/>
        public void NotifyPlateParkingJSONAsync(string jsonIn, object userState) {
            if ((this.NotifyPlateParkingJSONOperationCompleted == null)) {
                this.NotifyPlateParkingJSONOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNotifyPlateParkingJSONOperationCompleted);
            }
            this.InvokeAsync("NotifyPlateParkingJSON", new object[] {
                        jsonIn}, this.NotifyPlateParkingJSONOperationCompleted, userState);
        }
        
        private void OnNotifyPlateParkingJSONOperationCompleted(object arg) {
            if ((this.NotifyPlateParkingJSONCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NotifyPlateParkingJSONCompleted(this, new NotifyPlateParkingJSONCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendPushWPNotificationsTo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SendPushWPNotificationsTo(string strUser, string strToastText1, string strToastText2, string strToastParam, string strTileTitle, int iTileCount, string strBackgroundImage) {
            object[] results = this.Invoke("SendPushWPNotificationsTo", new object[] {
                        strUser,
                        strToastText1,
                        strToastText2,
                        strToastParam,
                        strTileTitle,
                        iTileCount,
                        strBackgroundImage});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SendPushWPNotificationsToAsync(string strUser, string strToastText1, string strToastText2, string strToastParam, string strTileTitle, int iTileCount, string strBackgroundImage) {
            this.SendPushWPNotificationsToAsync(strUser, strToastText1, strToastText2, strToastParam, strTileTitle, iTileCount, strBackgroundImage, null);
        }
        
        /// <remarks/>
        public void SendPushWPNotificationsToAsync(string strUser, string strToastText1, string strToastText2, string strToastParam, string strTileTitle, int iTileCount, string strBackgroundImage, object userState) {
            if ((this.SendPushWPNotificationsToOperationCompleted == null)) {
                this.SendPushWPNotificationsToOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendPushWPNotificationsToOperationCompleted);
            }
            this.InvokeAsync("SendPushWPNotificationsTo", new object[] {
                        strUser,
                        strToastText1,
                        strToastText2,
                        strToastParam,
                        strTileTitle,
                        iTileCount,
                        strBackgroundImage}, this.SendPushWPNotificationsToOperationCompleted, userState);
        }
        
        private void OnSendPushWPNotificationsToOperationCompleted(object arg) {
            if ((this.SendPushWPNotificationsToCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendPushWPNotificationsToCompleted(this, new SendPushWPNotificationsToCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendPushAndroidNotificationsTo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SendPushAndroidNotificationsTo(string strUser, string strAndroidRawData) {
            object[] results = this.Invoke("SendPushAndroidNotificationsTo", new object[] {
                        strUser,
                        strAndroidRawData});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SendPushAndroidNotificationsToAsync(string strUser, string strAndroidRawData) {
            this.SendPushAndroidNotificationsToAsync(strUser, strAndroidRawData, null);
        }
        
        /// <remarks/>
        public void SendPushAndroidNotificationsToAsync(string strUser, string strAndroidRawData, object userState) {
            if ((this.SendPushAndroidNotificationsToOperationCompleted == null)) {
                this.SendPushAndroidNotificationsToOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendPushAndroidNotificationsToOperationCompleted);
            }
            this.InvokeAsync("SendPushAndroidNotificationsTo", new object[] {
                        strUser,
                        strAndroidRawData}, this.SendPushAndroidNotificationsToOperationCompleted, userState);
        }
        
        private void OnSendPushAndroidNotificationsToOperationCompleted(object arg) {
            if ((this.SendPushAndroidNotificationsToCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendPushAndroidNotificationsToCompleted(this, new SendPushAndroidNotificationsToCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void NotifyPlateFineCompletedEventHandler(object sender, NotifyPlateFineCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NotifyPlateFineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NotifyPlateFineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void NotifyPlateFineJSONCompletedEventHandler(object sender, NotifyPlateFineJSONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NotifyPlateFineJSONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NotifyPlateFineJSONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void NotifyPlateParkingCompletedEventHandler(object sender, NotifyPlateParkingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NotifyPlateParkingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NotifyPlateParkingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void NotifyPlateParkingJSONCompletedEventHandler(object sender, NotifyPlateParkingJSONCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NotifyPlateParkingJSONCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NotifyPlateParkingJSONCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SendPushWPNotificationsToCompletedEventHandler(object sender, SendPushWPNotificationsToCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendPushWPNotificationsToCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendPushWPNotificationsToCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SendPushAndroidNotificationsToCompletedEventHandler(object sender, SendPushAndroidNotificationsToCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendPushAndroidNotificationsToCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendPushAndroidNotificationsToCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591